cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - stable
before_script:
  - psql -c 'create database banka_test_db; ' -U postgres
  - npm install -g sequelize-cli
script: 
  - "npm test"
services: 
  - postgresql
